name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/eshop-front:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/eshop-front:latest --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} .

    - name: Log in to Docker Hub
      if: success()
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/eshop-front --all-tags
